import type { Metadata } from 'next';
import { Kanit } from 'next/font/google';
import './globals.css';

const font = Kanit({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      suppressHydrationWarning 
      className={`${font.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
